# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa59a1f71df3dc2eba4ac61cc594219d7beab010d5f756bd2ac112edbd98dfc0f68981a6fb2bc50113279ef1f87835f5ef9a312222df16e4905f55794d7e7d4e

test:
  secret_key_base: 1e9e292033f2d75b3d98723a86c2027f7cc08b30fd3bef6e2e42424755e3580192f182fbb97c926f975bf27b8df6921be80d137ca0aaff0997c63cb9010c25c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
